const data = {
  products: [
    {
      name: 'Free Shirts',
      slug: 'free-shirts',
      categories: 'shirets',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
    {
      name: 'Free Shirts 1',
      slug: 'free-shirts-1',
      categories: 'shirets',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
    {
      name: 'Free Shirts 2',
      slug: 'free-shirts-2',
      categories: 'shirets',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
    {
      name: 'Free Shirts 3',
      slug: 'free-shirts-3',
      categories: 'shirets',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
    {
      name: 'Free Shirts 4',
      slug: 'free-shirts-4',
      categories: 'shirets',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
    {
      name: 'Free Shirts 5',
      slug: 'free-shirts-5',
      categories: 'shirets',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shitr',
    },
  ],
};
export default data;
